#python script to fimd the k nearest neighbors of a given point

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import voronoi_plot_2d, Voronoi


#function to find the distance between two points

In [3]:
def distance(x1,x2):
    return np.sqrt(sum((x1-x2)**2))

#read the csv file

In [5]:
data = np.loadtxt('data.csv', delimiter=',')
x = data[:,0]
y = data[:,1]
label = data[:,2]

In [6]:
print(x)
print(y)
print(label)

[4. 6. 7. 5. 8.]
[3. 7. 8. 5. 8.]
[0. 0. 1. 0. 1.]


#input the marks of maths and cs

In [8]:
maths = float(input("Enter the marks of maths: "))
cs = float(input("Enter the marks of cs: "))

#input the value of k for k nearest neighbors

In [9]:
k = int(input("Enter the value of k: "))